/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstrumentationManager */

#ifndef _Included_InstrumentationManager
#define _Included_InstrumentationManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstrumentationManager
 * Method:    getInstrumentation
 * Signature: ()Ljava/lang/instrument/Instrumentation;
 */
JNIEXPORT jobject JNICALL Java_InstrumentationManager_getInstrumentation
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
